export const CONTACT_LIST = "Contacts"
export const CONTACT_DETAIL = "Contact detail"
export const CREATE_CONTACT = "Create Contact"
export const SETTING = "setting"
export const LOGIN = "login"
export const REGISTER = "register"
